### ISSUE TITLE
[BUG] Tons of Exceptions in system logs

### ISSUE THREAD

**Issue by usedragon** [nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker#21] opened 2020-06-24 22:00 UTC
**Do you own the TS3 Integration application?**
https://invisioncommunity.com/profile/219253-goza/

**Describe the bug**
Few of our community ran into an issue last night where the site went bonkers with tons of exception thrown and the site going 500's.
```
OutOfRangeException:  (0)
#0 /var/www/forums.rmog.us/system/Theme/Theme.php(373): IPS\Patterns\_ActiveRecord::load(0)
#1 /var/www/forums.rmog.us/system/Dispatcher/Standard.php(54): IPS\_Theme::i()
#2 /var/www/forums.rmog.us/init.php(820) : eval()'d code(43): IPS\Dispatcher\_Standard::baseCss()
#3 /var/www/forums.rmog.us/init.php(820) : eval()'d code(14): IPS\Dispatcher\patreonintegration_hook_JsCss::baseCss()
#4 /var/www/forums.rmog.us/system/Dispatcher/Front.php(673): IPS\Dispatcher\brilliantdiscord_hook_standardDispatcherCss::baseCss()
#5 /var/www/forums.rmog.us/system/Dispatcher/Front.php(77): IPS\Dispatcher\_Front::baseCss()
#6 /var/www/forums.rmog.us/init.php(820) : eval()'d code(22): IPS\Dispatcher\_Front->init()
#7 /var/www/forums.rmog.us/system/Dispatcher/Dispatcher.php(109): IPS\Dispatcher\ts3integration_hook_UUIDRequired->init()
#8 /var/www/forums.rmog.us/index.php(13): IPS\_Dispatcher::i()
#9 {main}

#0 /var/www/forums.rmog.us/init.php(898): IPS\_Log::log('OutOfRangeExcep...', 'uncaught_except...')
#1 [internal function]: IPS\IPS::exceptionHandler(Object(OutOfRangeException))
#2 {main}
```
```
Error: Call to a member function stripQueryString() on null (0)
#0 /var/www/forums.rmog.us/system/Dispatcher/Front.php(85): IPS\Dispatcher\_Front->checkUrl()
#1 /var/www/forums.rmog.us/init.php(820) : eval()'d code(22): IPS\Dispatcher\_Front->init()
#2 /var/www/forums.rmog.us/system/Dispatcher/Dispatcher.php(109): IPS\Dispatcher\ts3integration_hook_UUIDRequired->init()
#3 /var/www/forums.rmog.us/index.php(13): IPS\_Dispatcher::i()
#4 {main}

#0 /var/www/forums.rmog.us/init.php(898): IPS\_Log::log('Error: Call to ...', 'uncaught_except...')
#1 [internal function]: IPS\IPS::exceptionHandler(Object(Error))
#2 {main}
```

```
Error: Call to undefined method stdClass::language() (0)
#0 /var/www/forums.rmog.us/system/Dispatcher/Front.php(107): IPS\Dispatcher\_Standard->init()
#1 /var/www/forums.rmog.us/init.php(820) : eval()'d code(22): IPS\Dispatcher\_Front->init()
#2 /var/www/forums.rmog.us/system/Dispatcher/Dispatcher.php(109): IPS\Dispatcher\ts3integration_hook_UUIDRequired->init()
#3 /var/www/forums.rmog.us/index.php(13): IPS\_Dispatcher::i()
#4 {main}

#0 /var/www/forums.rmog.us/init.php(898): IPS\_Log::log('Error: Call to ...', 'uncaught_except...')
#1 [internal function]: IPS\IPS::exceptionHandler(Object(Error))
#2 {main}
```

Pretty much everything linking back to IPS\Dispatcher\ts3integration_hook_UUIDRequired->init()

**To Reproduce**
Logs above

**Expected behavior**
Got reports the site went bonkers. Gotten tons of exceptions thrown and the site was 500'ing.

**Screenshots**
No screenshots 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 83.0.4529.99 (Official Build) (32-bit)

**Additional context**

**Comment by nathan-fiscaletti** [comment] 2020-06-24 23:21
DId you recently update PHP, MySql or your IPS installation?

**Comment by usedragon** [comment] 2020-06-24 23:27
I've asked the co-owner about it. During that time, he change file storage from MYSQL to file system.

**Comment by nathan-fiscaletti** [comment] 2020-06-24 23:54
> He change file storage from MYSQL to file system.

I'm not sure if this makes sense. MySql is a Database where as the file system is where files are stored, they're two very different things. Can you have him take a look at this ticket?

**Comment by nathan-fiscaletti** [comment] 2020-06-24 23:58
If you changed your database back end, you may need to un-install, re-install and then re-configure your TS3 application as the configuration it normally uses is now not available (it was stored in SQL)

**Comment by Stoopler** [comment] 2020-06-25 00:03
Nathan,

I changed our data storage from MySQL to File System last night, our database itself has not changed.

**Comment by nathan-fiscaletti** [comment] 2020-06-25 00:28
I don't believe this should cause any problems, however can you try switching it back to see if the problem resolves itself? If this poses an issue, and you don't mind terribly, can you give me ACP access and i can try to take a look tomorrow morning. 

If you want to try a quick fix and don't mind doing it, you can try uninstalling the TS3 application, re-installing it and then re-configuring it. Keeping in mind that uninstalling the application means that you will lose all of your TS3 configurations.

**Comment by nathan-fiscaletti** [comment] 2020-06-25 00:33
Can you also share what version of Invision Community you are running?

**Comment by usedragon** [comment] 2020-06-25 00:36
4.4.10

**Comment by nathan-fiscaletti** [comment] 2020-06-25 00:39
So, for the time being, I would refer to my last comment. Let me know if nothing works or if you'd like to provide me with an ACP account so that I can attempt to help you out. If you do choose to give me ACP access and have me help out, you can send me a DM on the IPS forums with login credentials instead of posting it publicly here. (I may also need SQL credentials, however, I would only need read access to diagnose the issue)

My IPS profile is: https://invisioncommunity.com/profile/590869-mrfisc/

Like I said earlier, I may not be available to help out in this way until tomorrow.

**Comment by usedragon** [comment] 2020-06-25 00:45
Sent you message.

**Comment by nathan-fiscaletti** [comment] 2020-06-25 20:17
I responded on IPS as you seem to have sent me a password but no username.

**Comment by nathan-fiscaletti** [comment] 2020-06-27 13:42
After looking into this, I don't believe the TS3 application to be the culprit. While it's included in all of the stack traces, I believe it's due to the way in which IPS handles class Hooks, not that TS3 is actually the cause.

Each of the stack traces you supplied is for a vastly different error. They don't seem to be related to each other.

For example:

`stripQueryString()` is causing one of the issues, which is a member function of the ActiveRecord class. Somewhere in that stack the ActiveRecord object that is being used resulted in a null object, causing this error. We do not use `stripQueryString()` anywhere in the TS3 application.

These issues seem related to either a corrupt IPS installation or a problematic third party application you have installed. 

One way to debug this is to do the following:

1) Figure out how to reliably reproduce the problem.
2) Disable applications / plugins one-by-one and attempt to reproduce the problem again as you do.
3) Once you are no longer able to re-produce the problem, you know which third party application is causing it.

If after doing this type of testing, if you are able to conclude that the TS3 application is the culprit, I can look further into this. 

However, the code that is being executed within the mentioned hook (`ts3integration_hook_UUIDRequired`) is very minimal. There isn't a lot happening there, and definitely nothing that should be causing errors such as this.

For the time being I'm going to close this issue, however, if you can do further testing and conclude that the TS3 application is the culprit, feel free to open the issue back up.

**Closed as completed** 2020-06-27 13:44 UTC
Labels: bug
